data_dir: data
cache_dir: .cache
models_dir: models

defaults:
  - override hydra/job_logging: custom

hydra:
  run:
    dir: ./log/${hydra:job.name}/${now:%Y-%m-%d}/${now:%H-%M}

api:
  cache_dir: ${cache_dir}
  device: 0
  detector:
    _target_: inference.wrapper.yolov8_wrapper.YoloV8Wrapper
    weight_path: ${models_dir}/yolov8m.pt
    device: ${api.device}
    # classes: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,71,73,74,75,76,77,78,79]
    # classes: 0
    classes: [0,1,2,3,5,6,7,15,16,17,18,19,20,21,22,23]
    conf: 0.4
    imgsz: 640


server:
  host: 0.0.0.0
  port: 8000
  root_path: "/"
  workers: 1


# names = ['person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train', 'truck', 'boat', 'traffic light',
#          'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow',
#          'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee',
#          'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard',
#          'tennis racket', 'bottle', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple',
#          'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair', 'couch',
#          'potted plant', 'bed', 'dining table', 'toilet', 'tv', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone',
#          'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy bear',
#          'hair drier', 'toothbrush']